---
title: "Group4_EDA"
author: "Adeel Qureshi, Cleveland Johnson, Nathan Deinlein, and Puri Rudick"
date: "5/23/2021"
output: html_document
editor_options: 
chunk_output_type: console
---

```{r setup, include=FALSE}
library(dplyr)
library(ggplot2)
library(rworldmap)
library(corrplot)
library(tidyr)
library(countrycode)
library(PerformanceAnalytics)
library(naniar)
library(car)
library(leaps)
library(glmnet)
library(caret)
library(broom)
```

```{r}
# Read in dataset
lifeExpec = read.csv("Life Expectancy Data.csv",header = TRUE)

# Observe dataset in general
dim(lifeExpec)
str(lifeExpec)
head(lifeExpec)

# Add continent column to the dataset
lifeExpec$continent <- countrycode(sourcevar = lifeExpec$Country,
                                   origin = "country.name",
                                   destination = "continent")

# Edit 3 country names
lifeExpec$CountrytoMatch <- as.character(lifeExpec$Country)
lifeExpec$CountrytoMatch[lifeExpec$CountrytoMatch == "Côte d'Ivoire"] <- "Cote d'Ivoire"
lifeExpec$CountrytoMatch[lifeExpec$CountrytoMatch == "Cabo Verde"] <- "Cape Verde"
lifeExpec$CountrytoMatch[lifeExpec$CountrytoMatch == "Czechia"] <- "Czech Republic"

# Statistics summary table for all variables
summary(lifeExpec)

```

# Check and clean up data record for each country
```{r}
unique(lifeExpec$Country) # There are 193 countries in total
unique(lifeExpec$Year) # 16 years of data collection from 2000 to 2015

# There are 10 countries that do not have 16 years of data.  They all have only 2013 data record
lifeExpec %>% group_by(Country) %>% 
  filter(n() != 16)

# Excluded countries with < 16 years of data collection from the dataset
lifeExpec <- lifeExpec %>% 
  group_by(Country) %>% 
  filter(n() == 16)

# Check if there is any country with duplicated year records
lifeExpec %>% group_by(Country, Year) %>% 
  filter(n() > 1) %>% 
  summarize(n=n()) # There is none

# Quick boxplot to see if any country have years of data collection differ from 2000 to 2015. --There is none.
#lifeExpec %>% ggplot(aes(x=Country, y=Year)) + 
#  geom_boxplot() +
#  coord_flip()

# At this point, all 193 - 10 = 183 countries have all 16 years of data record from 2000 to 2015.  Total in 2,928 (183*16) rows.
# Create summary table
summary(lifeExpec)
```

# Address the missing values
```{r}
# Check for missing value in each column
missing.values_summary <- lifeExpec %>%
  gather(key = "key", value = "val") %>%
  mutate(is.missing = is.na(val)) %>%
  group_by(key, is.missing) %>%
  summarise(num.missing = n()) %>%
  filter(is.missing==T) %>%
  select(-is.missing) %>%
  arrange(desc(num.missing))

missing.values_summary

# Missing values % in each column
missing.values <- lifeExpec %>%
  gather(key = "key", value = "val") %>%
  mutate(isna = is.na(val)) %>%
  group_by(key) %>%
  mutate(total = n()) %>%
  group_by(key, total, isna) %>%
  summarise(num.isna = n()) %>%
  mutate(pct = num.isna / total * 100)

mm <- missing.values %>% filter(pct != 100)
mm <- mm %>% group_by(key) %>% mutate(max.per.group = max(as.numeric(pct)))

mm %>% ggplot(aes(x= reorder(key, desc(max.per.group)), y=pct, fill=isna)) + geom_bar(stat="identity") + 
  geom_text(aes(label=paste0(round(pct,1),"%")), 
            position = position_stack(vjust = .5), size = 3.5) + 
  labs(title = 'Percentage of missing values', x = 'Variable', y = '% of Missing Values') +
  theme_classic() + scale_fill_manual(name = "", 
                    values = c('lightblue2', 'lightsalmon2'), 
                    labels = c("Present", "Missing")) + coord_flip()


# Missing value in each observation
missing_col <- subset(lifeExpec, select = c(levels))
vis_miss(missing_col, sort_miss=TRUE)

# We will keep all data for now.  Will decide on method to treat missing data later after we figure it out about the variables that we would like to include in the model
# In my opinion, deleting all missing value will cause too much information lost


# Missing values by country
lifeExpec %>% 
  group_by(Country) %>% 
  summarise_all(~sum(is.na(.))) %>% 
  transmute(Country, sumNA = rowSums(.[-1]))

```

###### Life expectancy correlation coefficient for numerical variables
```{r}
# Correlation coefficient for numerical columns
num_col <- subset(lifeExpec, select = -c(Year, Country, CountrytoMatch, Status, continent))

M <- cor(num_col, use = "complete.obs")
corrplot(M, use="complete.obs")

chart.Correlation(num_col, histogram=TRUE, pch=19)

```

# Test on transformation on good candidate variables
```{r Transformation of Income.composition.of.resources and Schooling}
# Remove 'zero' from observations for both Income.composition.of.resources and Schooling

income_comp <- subset(lifeExpec, select = c(Life.expectancy, Income.composition.of.resources))
income_comp <- income_comp[income_comp$Income.composition.of.resources != 0, ]

chart.Correlation(income_comp, histogram=TRUE, pch=19)
# Corr. coefficient between LifeEpactancy and Income.composition.of.resources changed from 0.72 to 0.89

schooling <- subset(lifeExpec, select = c(Life.expectancy, Schooling))
schooling <- schooling[schooling$Schooling != 0, ]

chart.Correlation(schooling, histogram=TRUE, pch=19)
# Corr. coefficient between LifeEpactancy and schooling changed from 0.75 to 0.78

# Both Income.composition.of.resources and Schooling are still good candidates
```

```{r Transformation of GDP, Alcohol, BMI}
lifeExpec %>% ggplot(aes(x=BMI, y=Life.expectancy)) + geom_point() + geom_smooth(method="loess") + geom_jitter()

summary(lifeExpec$BMI)
# The lowest BMI ever recorded is 7.5.  Mean BMI of 12 is the lower limit for human survival.
lifeExpec %>% filter(BMI<12) %>% select(BMI) %>% arrange(BMI)
BMI_clean <- lifeExpec %>% filter(BMI>=12) %>% select(Life.expectancy, BMI) %>% arrange(BMI)
dim(BMI_clean)

BMI_clean %>% ggplot(aes(x=log(BMI), y=Life.expectancy)) + geom_point() + geom_smooth(method="lm") +geom_jitter()

attach(BMI_clean)
par(mfrow=c(1,3))
plot(log(BMI), Life.expectancy, xlab="BMI", ylab="Life Expectancy")
BMI.model <-lm(Life.expectancy~log(BMI))
plot(BMI.model$fitted.values,BMI.model$residuals, xlab="Fitted Values", ylab="Residuals")
plot(log(BMI), BMI.model$residuals, xlab="BMI", ylab="Residuals")

par(mfrow=c(2,2))
plot(BMI.model)

cor(log(BMI),Life.expectancy)
#BMI Change from .57 to .72

summary(lifeExpec$Alcohol)
#193 NAs
Alcohol_clean <- lifeExpec %>% filter(!is.na(Alcohol)) %>% arrange(Alcohol)
summary(Alcohol_clean$Alcohol)
attach(Alcohol_clean)
Alcohol.model <-lm(log(Life.expectancy)~Alcohol)
par(mfrow=c(1,2))
plot(Alcohol.model$fitted.values,Alcohol.model$residuals, xlab="Fitted Values", ylab="Residuals")
plot(Alcohol, Alcohol.model$residuals, xlab="Alcohol Cons.", ylab="Residuals")

# Alcohol has a nonconstant variance, when both before and after log transformed
# Transforming life expectancy does not help the varaince either.
# Remove Alcohol as a good candidate.

summary(lifeExpec$GDP)
# 443 NAs
GDP_clean <- lifeExpec %>% filter(!is.na(GDP)) %>% arrange(GDP)
summary(GDP_clean$GDP)

attach(GDP_clean)
GDP.model <- lm(Life.expectancy~log(GDP))
par(mfrow=c(1,2))
plot(GDP.model$fitted.values,GDP.model$residuals, xlab="Fitted Values", ylab="Residuals")
plot(log(GDP), GDP.model$residuals, xlab="GDP.", ylab="Residuals")

cor(log(GDP), Life.expectancy)
# GDP chang from .46 to .598

```

```{r Transformation Diptheria, HIV, and Polio, echo = false}
attach(lifeExpec)
lifeExpec %>% ggplot(aes(x=Diphtheria, y=Life.expectancy)) + geom_point() + geom_smooth(method="loess") + geom_jitter()
oglm <- lm(Life.expectancy~Diphtheria, data = lifeExpec)
summary(oglm)

str(lifeExpec$Diphtheria)
summary(lifeExpec$Diphtheria)

# With diphtheria we are looking at vaccination rates. Anything below 25% would not be enough to impact a significant portion of the population. Thus these were removed.
DIP_clean <- lifeExpec %>% filter(Diphtheria>=25) %>% select(Life.expectancy, Diphtheria)
dim(DIP_clean)

DIP_clean %>% ggplot(aes(x=Diphtheria, y=Life.expectancy)) + geom_point() + geom_smooth(method="lm") +geom_jitter()

attach(DIP_clean)
DIPlm <- lm(Life.expectancy~Diphtheria, data = DIP_clean)
par(mfrow=c(2,2))
plot(DIPlm)
summary(DIPlm)

# Tried additional transformations but none seemed to improve statistics beyond what we see in final model,
# adj R-squared changed from .22 to .38

# HIV deaths per 1000 in under 5 range starting correlation
HIV <- lifeExpec %>% filter(!is.na(HIV.AIDS))
summary(HIV$HIV.AIDS)
HIV %>% ggplot(aes(x=HIV.AIDS, y = Life.expectancy)) +geom_point() + geom_smooth(method = "lm") + geom_jitter()
HIV %>% ggplot(aes(x=log(HIV.AIDS), y = log(Life.expectancy))) +geom_point() + geom_smooth(method = "lm") + geom_jitter()
HIVoglm <- lm(Life.expectancy~HIV.AIDS, data = lifeExpec)
summary(HIVoglm)

attach(HIV)
HIVlm <-lm(log(Life.expectancy)~log(HIV.AIDS))
plot(HIVlm)
summary(HIVlm)

# transformation of both x and y variables allows residual tables to look best.
# Adj R-squared looks much better going from .31 to .68


# Polio
Polio1 <- lifeExpec %>% filter(!is.na(Polio))
summary(Polio$Polio)
Polio1 %>% ggplot(aes(x=Polio, y = Life.expectancy)) +geom_point() + geom_smooth(method = "lm") + geom_jitter()

#similar to Diphtheria vaccination rates nothing below 25 should have a reasonable effect on total population.
Polio_clean <- Polio1 %>% filter(Polio >= 25)

Polio_clean %>% ggplot(aes(x=Polio, y = Life.expectancy)) +geom_point() + geom_smooth(method = "lm") + geom_jitter()
poliooglm <- lm(Life.expectancy~Polio, data = lifeExpec)
summary(poliooglm)

attach(Polio_clean)
poliolm <-lm(Life.expectancy~Polio, data = Polio_clean)
plot(poliolm)
summary(poliolm)

#No drastic improvements adj R-Squared went from .22 to .38

```

```{r infant.deaths, Avg_ChildMort, Adult.Mortality echo = false}
#EDA for the life expectancy data

data <- lifeExpec
str(data)

summary(data)

head(data, 5)

#check NA's
table(is.na(data))
rowSums(is.na(data))
apply(is.na(data), 2, sum)

#life expectancy for all the countries
ggplot(data, aes(Life.expectancy)) + geom_histogram(bins = 10) + facet_grid(vars(continent))

#life expectancy for developer vs developed
ggplot(data, aes(Life.expectancy)) + geom_histogram(bins = 10) + facet_grid(vars(Status))

#life expectancy year vs life expectancy
ggplot(data, aes(Year, Life.expectancy, color = Status)) + geom_point(size = 4) + ggtitle(("Life Expectancy Developing Countries vs Developed Countries"))

#descriptive statistics removing the nas
data %>% drop_na(Life.expectancy) %>% group_by(Status) %>% summarize(Avg_lifexp = mean(Life.expectancy), Avg_ChildMort = mean(infant.deaths), Avg_AdultMort = mean(Adult.Mortality))

#descriptive statistics by continent
data %>% drop_na(Life.expectancy) %>% group_by(continent) %>% summarize(Avg_lifexp = mean(Life.expectancy), Avg_ChildMort = mean(infant.deaths), Avg_AdultMort = mean(Adult.Mortality))


#life expectancy of the developed and developing countries
data %>% drop_na(Life.expectancy) %>% group_by(Year) %>% summarize(Avg_lifexp = mean(Life.expectancy), Avg_ChildMort = mean(infant.deaths), Avg_AdultMort = mean(Adult.Mortality)) %>% ggplot() + geom_smooth(aes(Year, Avg_ChildMort), color = 'red', se = FALSE) + geom_smooth(aes(Year, Avg_AdultMort), color = 'blue', se = FALSE)

clean_data <- data %>% select(-continent, -Country, -Year, -Status)

head(clean_data, 5)

#relationship testing for adult mortality & infant deaths
ggplot(clean_data, aes(Adult.Mortality, infant.deaths )) + geom_point()

#correlation between Adult Mortality and Life Expectancy
clean_data %>% summarize(N = n(), cor(Adult.Mortality, as.integer(Life.expectancy), use = "pairwise.complete.obs"))

clean_data %>% summarize(N = n(), cor(Adult.Mortality, infant.deaths, use = "pairwise.complete.obs"))

clean_data %>% summarize(N = n(), cor(log(Adult.Mortality), log(infant.deaths), use = "pairwise.complete.obs"))

#relationship testing for adult mortality & infant deaths
ggplot(clean_data, aes(Adult.Mortality, infant.deaths)) + geom_point()

ggplot(clean_data, aes(Adult.Mortality, infant.deaths)) + geom_point() + scale_x_log10() + scale_y_log10()
```

```{r Life expectancy trends in categorical variables}
# Boxplot of life expectancy vs. year shows that both mean and median of life expectancy is increasing every year since average (mean) 66.75 in 2000 to average (mean) 71.62 in 2015
Life.expectancy_means <- aggregate(Life.expectancy ~ Year, lifeExpec, mean)

lifeExpec %>% ggplot(aes(x=Year, y=Life.expectancy, group=Year)) + 
  geom_boxplot() + 
  stat_summary(fun=mean, colour="darkred", geom="point", 
               shape=18, size=3, show.legend=FALSE) + 
  geom_text(data=Life.expectancy_means, aes(label = format(round(Life.expectancy, 2), nsmall = 2), y = Life.expectancy - 2.5, col = "darkred")) +
  theme(legend.position = "none") +
  coord_flip()


# Boxplot of life expectancy vs. continent also shows life expectancy increasing trend
lifeExpec %>% ggplot(aes(x=Year, y=Life.expectancy, group=Year)) + 
  geom_boxplot(aes(fill=continent)) +
  facet_grid(continent ~ .)


# Wold map displays life expectancy in general (median value from 2000 - 2015) for each country.  Africa has the lowest life expectancy, follows by Asia.

medianExpec <- aggregate(lifeExpec[, 4], list(lifeExpec$CountrytoMatch), median)
names(medianExpec)[names(medianExpec)=="Group.1"] <- "Country"

countryMap <- joinCountryData2Map(lifeExpec, joinCode = "NAME", nameJoinColumn = "Country")

map <- joinCountryData2Map(
       medianExpec,
       joinCode       = "NAME",
       nameJoinColumn = "Country",
       verbose = TRUE
     )

mapCountryData(map,
               mapTitle = "Median Life Expectancy (2000 - 2015)",
               nameColumnToPlot = "Life.expectancy",
               catMethod = "fixedWidth"
)

# Boxplot life expectancy vs. continent also shows the same trend
lifeExpec %>% ggplot(aes(x=continent, y=Life.expectancy)) + 
  geom_boxplot(aes(fill=continent))

# Scatter plot life expectancy vs. adult martality color code by countrys' status.
lifeExpec %>% ggplot(aes(x=Life.expectancy, y=Adult.Mortality, shape=Status, color=Status)) +
  geom_jitter()

```

```{r EDA Misc.}

# Scatter plot life expectancy vs. adult mortality color code by countrys' status.
lifeExpec %>% ggplot(aes(x=Life.expectancy, y=Adult.Mortality, shape=Status, color=Status)) +
  geom_jitter()

lifeExpec %>% ggplot(aes(x=Life.expectancy, y=Schooling, shape=Status, color=Status)) +
  geom_jitter()

lifeExpec %>% ggplot(aes(x=Life.expectancy, y=Income.composition.of.resources, shape=Status, color=Status)) +
  geom_jitter()

lifeExpec %>% ggplot(aes(x=Life.expectancy, y=percentage.expenditure, shape=Status, color=Status)) +
  geom_jitter()

par("mfcol"=c(3, 4))
hist(lifeExpec$Life.expectancy, col="blue")
hist(lifeExpec$Adult.Mortality, col="green")
hist(lifeExpec$infant.deaths, col="red") 
hist(lifeExpec$Alcohol, col="blue")
hist(lifeExpec$percentage.expenditure, col="green")
hist(lifeExpec$under.five.deaths, col="red") 
hist(lifeExpec$Total.expenditure, col="green")
hist(lifeExpec$GDP, col="green")
hist(lifeExpec$Population, col="green")
hist(lifeExpec$Income.composition.of.resources, col="green")
hist(lifeExpec$Schooling, col="green")
par("mfcol"=c(1, 1))

par("mfcol"=c(2, 4))
hist(lifeExpec$BMI, col="green")
hist(lifeExpec$Hepatitis.B, col="red")
hist(lifeExpec$Measles, col="blue")
hist(lifeExpec$Polio, col="blue")
hist(lifeExpec$Diphtheria, col="red") 
hist(lifeExpec$HIV.AIDS, col="blue")
hist(lifeExpec$thinness..1.19.years, col="red")
hist(lifeExpec$thinness..1.19.years, col="blue")
par("mfcol"=c(1, 1))
```


# Final Dataset
```{r}
# Final dataset, lifeExpec_final, only includes Life.expectancy, Status, continent, BMI, HIV.AIDS, GDP, Income.composition.of.resources, and Schooling
lifeExpec_final <- subset(lifeExpec, select = -c(Country, CountrytoMatch, Year, Adult.Mortality, Alcohol, percentage.expenditure, infant.deaths, Hepatitis.B, Measles, under.five.deaths, Total.expenditure, Population, thinness..1.19.years, thinness.5.9.years, Polio, Diphtheria))


summary(lifeExpec_final)


# Lowest BMI to survive is 12 so we replace everything <12 and NA with overall mean BMI then log transform
lifeExpec_final$BMI <- replace(lifeExpec_final$BMI, lifeExpec_final$BMI < 12, NA)

lifeExpec_final$BMI[is.na(lifeExpec_final$BMI)]<-mean(lifeExpec_final$BMI,na.rm=TRUE)
lifeExpec_final$BMI

lifeExpec_final$BMI_log <- log(lifeExpec_final$BMI)


# Replace zero for Income.composition.of.resources with its mean
lifeExpec_final$Income.composition.of.resources <- replace(lifeExpec_final$Income.composition.of.resources,
                                                           lifeExpec_final$Income.composition.of.resources == 0, NA)
summary(lifeExpec_final$Income.composition.of.resources)

lifeExpec_final$Income.composition.of.resources[is.na(lifeExpec_final$Income.composition.of.resources)] <-
  mean(lifeExpec_final$Income.composition.of.resources,na.rm=TRUE)
lifeExpec_final$Income.composition.of.resources


# Replace zero for Schooling with its mean
lifeExpec_final$Schooling <- replace(lifeExpec_final$Schooling,
                                     lifeExpec_final$Schooling == 0, NA)
summary(lifeExpec_final$Schooling)

lifeExpec_final$Schooling[is.na(lifeExpec_final$Schooling)] <-
  mean(lifeExpec_final$Schooling,na.rm=TRUE)
lifeExpec_final$Schooling


# Replace GDP's NA with its mean then log transform
summary(lifeExpec_final$GDP)
lifeExpec_final$GDP[is.na(lifeExpec_final$GDP)]<-mean(lifeExpec_final$GDP,na.rm=TRUE)
lifeExpec_final$GDP

lifeExpec_final$GDP_log <- log(lifeExpec_final$GDP)


# Replace HIV.AIDS's NA with its mean then log transform
summary(lifeExpec_final$HIV.AIDS)
lifeExpec_final$HIV.AIDS[is.na(lifeExpec_final$HIV.AIDS)]<-mean(lifeExpec_final$HIV.AIDS,na.rm=TRUE)
lifeExpec_final$HIV.AIDS

lifeExpec_final$HIV.AIDS_log <- log(lifeExpec_final$HIV.AIDS)
```

# Correlation plot for final dataset and VIF value
```{r}
# Plot correlation chart for final dataset numerical variables

## Original variables before transformation included
lifeExpec_final_numCol_Orig <- subset(lifeExpec_final, select = -c(Status, continent))
chart.Correlation(lifeExpec_final_numCol_Orig, histogram=TRUE, pch=19)

## Remove unlog BMI, GDP, and HIV.AIDS 
lifeExpec_final_numCol <- subset(lifeExpec_final, select = -c(Status, continent, BMI, GDP, HIV.AIDS))
chart.Correlation(lifeExpec_final_numCol, histogram=TRUE, pch=19)


lifeExpec_final <- subset(lifeExpec_final, select = -c(BMI, GDP, HIV.AIDS))
summary(lifeExpec_final)


# VIF for selected variables
## Refer to GVIF^(1/(2*Df)), Income_comp shows the highest VIF = 2.77, follows by Schooling at 2.33.
## Other variables shows VIF between 1.26 - 1.69
full.model <- lm(Life.expectancy~., data = lifeExpec_final)
vif(full.model)
```


```{r Test and train sets}
set.seed(7)
splitPerc = .85
trainIndices = sample(1:dim(lifeExpec_final)[1],round(splitPerc * dim(lifeExpec_final)[1]))
train = lifeExpec_final[trainIndices,]
test = lifeExpec_final[-trainIndices,]
```

# Build Simple Multiple Linear Regression Models
```{r}
#model1 <- lm(Life.expectancy ~ Status + continent + Income.composition.of.resources + Schooling + BMI_log + GDP_log + HIV.AIDS_log, data = train)

model.fwd = regsubsets(Life.expectancy~.,data=train, method="forward", nvmax=10)

summary(model.fwd)$adjr2
summary(model.fwd)$rss
summary(model.fwd)$bic

par(mfrow=c(1,3))
bics<-summary(model.fwd)$bic
plot(1:10,bics,type="l",ylab="BIC",xlab="# of predictors")
index<-which(bics==min(bics))
points(index,bics[index],col="red",pch=10)

adjr2<-summary(model.fwd)$adjr2
plot(1:10,adjr2,type="l",ylab="Adjusted R-squared",xlab="# of predictors")
index<-which(adjr2==max(adjr2))
points(index,adjr2[index],col="red",pch=10)

rss<-summary(model.fwd)$rss
plot(1:10,rss,type="l",ylab="train RSS",xlab="# of predictors")
index<-which(rss==min(rss))
points(index,rss[index],col="red",pch=10)

predict.regsubsets =function (object , newdata ,id ,...){
  form=as.formula (object$call [[2]])
  mat=model.matrix(form ,newdata)
  coefi=coef(object ,id=id)
  xvars=names(coefi)
  mat[,xvars]%*%coefi
}

testASE<-c()
#note my index is to 20 since that what I set it in regsubsets
for (i in 1:10){
  predictions <-predict.regsubsets(object=model.fwd,newdata=test,id=i)
  testASE[i]<-mean((test$Life.expectancy-predictions)^2)
}

par(mfrow=c(1,1))
plot(1:10,testASE,type="l",xlab="# of predictors",ylab="test vs train ASE")
index<-which(testASE==min(testASE))
points(index,testASE[index],col="red",pch=10)
rss<-summary(model.fwd)$rss
lines(1:10,rss/2489,lty=3,col="blue")  #Dividing by 100 since ASE=RSS/sample size

coef(model.fwd,8)

forward.final <-lm(Life.expectancy~Status+Income.composition.of.resources+Schooling+continent+BMI_log+HIV.AIDS_log, data= lifeExpec_final)

summary(forward.final)

x=model.matrix(Life.expectancy~.,train)[,-1]
y=train$Life.expectancy

xtest<-model.matrix(Life.expectancy~.,test)[,-1]
ytest<-test$Life.expectancy


grid=10^seq(10,-2, length =100)
lasso.mod=glmnet(x,y,alpha=1, lambda =grid)

cv.out=cv.glmnet(x,y,alpha=1) #alpha=1 performs LASSO
plot(cv.out)

bestlambda<-cv.out$lambda.min  #Optimal penalty parameter.  You can make this call visually.
lasso.pred=predict (lasso.mod ,s=bestlambda ,newx=xtest)

testMSE_LASSO<-mean((ytest-lasso.pred)^2)
testMSE_LASSO

coef(lasso.mod,s=bestlambda)

lasso.final <- lm(Life.expectancy~Status+Income.composition.of.resources+Schooling+continent+BMI_log+HIV.AIDS_log, data= lifeExpec_final)

summary(lasso.final)

par(mfrow=c(2,2))
plot(lasso.final)

lifeExpec_final[1126,]
lifeExpec_final[544,]
lifeExpec_final[864,]
lifeExpec[1126,]
lifeExpec[544,]
lifeExpec[864,]
```

```{r Complex MLR}

#complex model with interaction terms
fwdcpmodel1 <- regsubsets(Life.expectancy ~ Status + continent + Income.composition.of.resources + Schooling + BMI_log + GDP_log + HIV.AIDS_log + Income.composition.of.resources*Schooling + Income.composition.of.resources*BMI_log + Income.composition.of.resources*GDP_log + Schooling*BMI_log+Schooling*GDP_log + BMI_log*GDP_log, data = train, method = 'backward', nvmax=16)

#base check of model
summary(fwdcpmodel1)


#plot of BIC, ADJR^2, and RSS
bicsb <- summary(fwdcpmodel1)$bic
adjr2b <- summary(fwdcpmodel1)$adjr2
rssb <- summary(fwdcpmodel1)$rss

par(mfrow=c(1,3))
plot(1:16,bicsb,type="l",ylab="BIC",xlab="# of predictors",main= "Complex MLR BIC")
index<-which(bicsb==min(bicsb))
points(index,bicsb[index],col="red",pch=16)

plot(1:16,adjr2b,type="l",ylab="Adjusted R-squared",xlab="# of predictors",main= "Complex MLR ADJR2")
index<-which(adjr2b==max(adjr2b))
points(index,adjr2b[index],col="red",pch=16)

plot(1:16,rssb,type="l",ylab="train RSS",xlab="# of predictors",main= "Complex MLR RSS")
index<-which(rssb==min(rssb))
points(index,rssb[index],col="red",pch=16)



#Cross validation function
predict.regsubsets =function (object , newdata ,id ,...){
  form=as.formula (object$call [[2]])
  mat=model.matrix(form ,newdata)
  coefi=coef(object ,id=id)
  xvars=names(coefi)
  mat[,xvars]%*%coefi
}

#test versus train 
testASEb<-c()
for (i in 1:16){
  predictions <-predict.regsubsets(object=fwdcpmodel1,newdata=test,id=i)
  testASEb[i]<-mean((test$Life.expectancy-predictions)^2)
}

#test versus train graph
par(mfrow=c(1,1))
plot(1:16,testASEb,type="l",xlab="# of predictors",ylab="test vs train ASE",main= "Complex MLR Train vs Test")
index<-which(testASEb==min(testASEb))
points(index,testASEb[index],col="red",pch=13)
lines(1:16,rssb/2489,lty=3,col="blue")
testASEb

#11 seems to be optimum number of variables
coef(fwdcpmodel1,11)

#vif check before final model
vifcheckmodel <- lm(Life.expectancy ~ Status + continent +  Income.composition.of.resources + Schooling + BMI_log + HIV.AIDS_log + Income.composition.of.resources*Schooling + Income.composition.of.resources*BMI_log + Schooling*BMI_log, data = train)

#base check of model summary with VIF
par(mfrow=c(2,2))
plot(vifcheckmodel, main = "VIF Check Residual Plots")
summary(vifcheckmodel)
vif(vifcheckmodel)

vifcheckmodelb <- lm(Life.expectancy ~ Status + continent +  Income.composition.of.resources + HIV.AIDS_log + Schooling*BMI_log, data = train)

#base check of model summary with VIF
par(mfrow=c(2,2))
plot(vifcheckmodelb)
summary(vifcheckmodelb)
vif(vifcheckmodelb)

# Final model with VIF handled.
finalcpmodelb <- lm(Life.expectancy ~ Status + continent +  Income.composition.of.resources + Schooling*BMI_log+ HIV.AIDS_log, data = train)

# checkign final residual plots.
par(mfrow=c(2,2))
summary(finalcpmodelb)
plot(finalcpmodelb, main = "Final Model Residuals")


# Final Cross validation function
pred <- predict(finalcpmodelb, newdata = test)
finalase <- mse(test$Life.expectancy, pred)
finalase
```

```{r KNN regression Model}

head(lifeExpec_final)

lifeExpec_final$Life.expectancy <- as.numeric(lifeExpec_final$Life.expectancy)
lifeExpec_final$Income.composition.of.resources <- as.numeric(lifeExpec_final_numCol$Income.composition.of.resources)
lifeExpec_final$Schooling <- as.numeric(lifeExpec_final$Schooling)
lifeExpec_final$BMI_log <- as.numeric(lifeExpec_final$BMI_log)
lifeExpec_final$GDP_log <- as.numeric(lifeExpec_final$GDP_log)
lifeExpec_final$HIV.AIDS_log <- as.numeric(lifeExpec_final$HIV.AIDS_log)
lifeExpec_final$Status <- as.numeric(as.factor(lifeExpec_final$Status))
lifeExpec_final$continent <- as.numeric(as.factor(lifeExpec_final$continent))

head(lifeExpec_final, 5)

#estimation-validation split
lifeEst_trn_idx  <- sample(nrow(train), size = 0.8 * nrow(train))
lifeEst_est <- train[lifeEst_trn_idx,]
lifeEst_val <- train[-lifeEst_trn_idx,]

#verify data
head(train, 10)

#building KNN reg model
lifeEst_knn_01 <- knnreg(Life.expectancy ~ ., data = lifeExpec_final, k = 1)
lifeEst_knn_05 <- knnreg(Life.expectancy ~ ., data = lifeExpec_final, k = 5)
lifeEst_knn_10 <- knnreg(Life.expectancy ~ ., data = lifeExpec_final, k = 10)
lifeEst_knn_25 <- knnreg(Life.expectancy ~ ., data = lifeExpec_final, k = 25)

head(lifeEst_knn_10$learn$X)

dist(head(lifeEst_knn_10$learn$X))

#calculating the distance between the 3rd observation and 4th observation
sqrt(sum((lifeEst_knn_10$learn$X[3,] - lifeEst_knn_10$learn$X[4,])^4))

#test the predict function
predict(lifeEst_knn_10, lifeEst_val[1:50,])

#calculating the RMSE for the models
knn_mod_list = list(
lifeEst_knn_01 <- knnreg(Life.expectancy ~ ., data = lifeExpec_final, k = 1),
lifeEst_knn_05 <- knnreg(Life.expectancy ~ ., data = lifeExpec_final, k = 5),
lifeEst_knn_10 <- knnreg(Life.expectancy ~ ., data = lifeExpec_final, k = 10),
lifeEst_knn_25 <- knnreg(Life.expectancy ~ ., data = lifeExpec_final, k = 25)
)

train_knn(neighbors = 5)

knn_list <- lapply(1:50, train_knn)

knn_val_pred <- lapply(knn_list, predict, lifeEst_val)
knn_trn_pred <- lapply(knn_list, predict, lifeEst_est)

calc_rmse <- function(actual, predicted) (
  sqrt(mean((actual - predicted)^ 2))
)

sapply(knn_val_pred, calc_rmse, lifeEst_val$Life.expectancy)

#creating function for multiple k values
train_knn <- function(neighbors) {
  knnreg(Life.expectancy ~ ., data = lifeExpec_final, k = neighbors)
}

#create vectors for RMSE val and pred
knn_rmse_val <- sapply(knn_val_pred, calc_rmse, lifeEst_val$Life.expectancy)
knn_rmse_trn <- sapply(knn_trn_pred, calc_rmse, lifeEst_est$Life.expectancy)

#plot rmse 
plot(1:50, knn_rmse_val, type = "b", col = "dodgerblue", pch = 20, ylim = range(c(knn_rmse_val,knn_rmse_trn)), xlab = "k (number of neighbors", ylab = "RMSE", main = "Validation and Training RMSE vs k")
lines(1:50, knn_rmse_trn, col = "darkorange")
grid()
legend('bottomright', 
       c("Train RMSE","Validation RMSE"),
       col = c(2,1),
       lty = 1,
       pch = 20)


#plot the predict function KNN K=1
pred01 <- predict(lifeEst_knn_01, lifeEst_val[1:50,])
actual <- lifeExpec_final[1:50,]


plot(actual$Life.expectancy, col = "black", ylab = "Actual vs Predicted Life Exp", main = "KNN K=1 Actual vs Predicted Life Expectancy")
points(1:50,pred01, col = "red")
grid()
legend('bottomright', 
       c("Prediction","Actual"),
       col = c(2,1),
       lty = 1,
       pch = 20)



#plot the predict function KNN K=5
pred05 <- predict(lifeEst_knn_05, lifeEst_val[1:50,])
actual <- lifeExpec_final[1:50,]


plot(actual$Life.expectancy, col = "black", ylab = "Actual vs Predicted Life Exp", main = "KNN K=5 Actual vs Predicted Life Expectancy")
points(1:50,pred05, col = "red")
grid()
legend('bottomright', 
       c("Prediction","Actual"),
       col = c(2,1),
       lty = 1,
       pch = 20)


#plot the predict function KNN K=10
pred10 <- predict(lifeEst_knn_10, lifeEst_val[1:50,])
actual <- lifeExpec_final[1:50,]


plot(actual$Life.expectancy, col = "black", ylab = "Actual vs Predicted Life Exp", main = "KNN K=10 Actual vs Predicted Life Expectancy")
points(1:50,pred10, col = "red")
grid()
legend('bottomright', 
       c("Prediction","Actual"),
       col = c(2,1),
       lty = 1,
       pch = 20)


#plot the predict function KNN K=25
pred25 <- predict(lifeEst_knn_25, lifeEst_val[1:50,])
actual <- lifeExpec_final[1:50,]


plot(actual$Life.expectancy, col = "black", ylab = "Actual vs Predicted Life Exp", main = "KNN K=25 Actual vs Predicted Life Expectancy")
points(1:50,pred25, col = "red")
grid()
legend('bottomright', 
       c("Prediction","Actual"),
       col = c(2,1),
       lty = 1,
       pch = 20)
```


